<a href="https://colab.research.google.com/github/woogi123/LA2/blob/main/%EA%B8%B0%EB%A7%90)ex03_evalue%2Bevactor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### 0. import libraries

In [ ]:
import numpy as np
import numpy.linalg as npl  # Linear Algebra
import matplotlib.pyplot as plt

In [ ]:
### eigen values & eigen vectors of A

In [ ]:
A = np.array([[4,2], [1,3]])  #np.vstack([[4,2],[1,3])
print("A:")
print (A, "\n")

e_values, e_vectors = npl.eig(A)
print("A의 고윳값 = ", e_values)
print("A의 고유벡터 = ", e_vectors) #길이가 1인 단위벡터로 나오기 때문에 자연수가 아님

#eigen vector u1, u2
u1 = np.vstack(e_vectors[:,0]) #모든 행에 대해서 0번째 열만 가지고 와라.
u2 = np.vstack(e_vectors[:,1]) #모든 행에 대해서 1번째 열만 가지고 와라.
print("ul: ", u1)
print("u2: ", u2)

#eigen value lambda 1, lambda 2
l1, l2 = e_values[0], e_values[1]
print("eigen values: ", l1, l2, "\n")

#check
print("Au1: ", np.dot(A, u1))
print("l1*u1: ", l1*u1)
print("Au2: ", np.dot(A, u2))
print("l2*u2: ", l2*u2)

A:
[[4 2]
 [1 3]] 

A의 고윳값 =  [5. 2.]
A의 고유벡터 =  [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
ul:  [[0.89442719]
 [0.4472136 ]]
u2:  [[-0.70710678]
 [ 0.70710678]]
eigen values:  5.0 2.0 

Au1:  [[4.47213595]
 [2.23606798]]
l1*u1:  [[4.47213595]
 [2.23606798]]
Au2:  [[-1.41421356]
 [ 1.41421356]]
l2*u2:  [[-1.41421356]
 [ 1.41421356]]


In [ ]:
B = np.array([[5,2,0],[2,5,0],[-3,4,6]])
print(B)
w2, V2 = npl.eig(B)   # (np.linalg.eig(B)도 가능) B의 고윳값과 고유벡터 계산
print("\nB의 고윳값 = ", w2)
print("B의 고유벡터 = ", V2)    #6에 대한 벡터 : 0,0,1 / 7에 대한 벡터 : 0.5,0.5,0.5 ...

[[ 5  2  0]
 [ 2  5  0]
 [-3  4  6]]

B의 고윳값 =  [6. 7. 3.]
B의 고유벡터 =  [[ 0.          0.57735027  0.36650833]
 [ 0.          0.57735027 -0.36650833]
 [ 1.          0.57735027  0.85518611]]
